//------------------------------------------------------------------------
// Copyright(c) 2024 yg331.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Comp001.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Comp001 VST3 (64Bit)"
#else
#define stringFileDescription	"Comp001 VST3"
#endif
#define stringCompanyName		"yg331\0"
#define stringLegalCopyright	"Copyright(c) 2024 yg331."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
